### ISSUE TITLE
Nutrient Indicators

### ISSUE THREAD

**Issue by nikkidix** [GTMNERR/swmp-quarter-report#1]
Since you can't always calculate TN, how about doing TKN instead? Can you also add DIN and PO4 graphs? I'm wondering if high P this spring at PI caused the high CHL (P-limitation?), but it's hard to tell when only looking at TP b/c algal cells have P in them.

**Comment by skdunnigan** [comment]
@nikkidix what kind of graphs would you like to see for DIN and PO4?

**Comment by skdunnigan** [comment]
@nikkidix will add PO4, but DIN is going to have the same issue as TN since it is calculated based on NO23.
