### ISSUE TITLE
Data Collection 2.0/Weather 2.1

### ISSUE THREAD

**Issue by katiepetrinec** [GTMNERR/swmp-quarter-report#2]
If this is a quarterly report then I suggest leaving out 'study period' and maybe even the CR10x information. Paragraph could be edited to something like this:

The meteorological data were collected using a Campbell Scientific CR1000 logger and sampled 15-min averages of 5-sec readings for air temperature, wind direction, and wind speed. The precipitation sensor measured 15-min totals.

And add (if you want to)
Historically, a CR10x-2M logger was used to collect meteorological data. The CR10X-2M logger sampled all weather station sensors every 5 sec and calculated both hourly and daily averages for air temperature, wind direction, and wind speed. Additionally, instantaneous samples of these parameters were recorded every 15 min. Precipitation data were summed and recorded as 15-minute, hourly, and daily totals.

**Comment by skdunnigan** [comment]
@katiepetrinec I like your suggestions! For text-based revisions, I can show you how to edit them directly in GitHub!!
