### ISSUE TITLE
Dates included

### ISSUE THREAD

**Issue by nikkidix** [GTMNERR/swmp-quarter-report#30]
I think it'd be helpful to include the date range included in each new report version, maybe in the title or on the front page somewhere. In this current version, info on the front page says data are updated each quarter, but there are data in Nov. Should you add that you sometimes include data after primary QC?

**Comment by skdunnigan** [comment]
So, I do have a date in the footer about the data being last updated, but I could either provide an explicit date range (which is also variable for each station/data type) or a blanket statement about data in the quarter for WQ and MET are QAQC'd thru a certain time frame?

**Comment by nikkidix** [comment]
nah, never mind. I think it's fine how you have it
