### ISSUE TITLE
DIN and TN

### ISSUE THREAD

**Issue by nikkidix** [GTMNERR/swmp-quarter-report#32]
I think for the purpose of this report, rather than not reporting DIN and TN when NO23 is undetectable, you should treat NO23 as zero or use the actual value even if it's below the MDL. Just add a statement about what you did.

**Comment by skdunnigan** [comment]
@katiepetrinec what do you think about this?

**Comment by skdunnigan** [comment]
@katiepetrinec when we enter data, do the values get reported at MDL or do we have the raw values?

**Comment by skdunnigan** [comment]
We can do that. I'll work on revisions for the next iteration

**Comment by skdunnigan** [comment]
Ammonium was added in commit [d643885](https://github.com/GTMNERR/swmp-quarter-report/commit/d6438850a6018f93ec1df5193fcb0c246cf58cfa)
