### ISSUE TITLE
4.1 Summary Paragraph 3

### ISSUE THREAD

**Issue by katiepetrinec** [GTMNERR/swmp-quarter-report#48]
Paragraph 3: Nor’easters brought heavy rainfall in March and in April which raised salinity at all stations.

Did you mean that the rainfall decreased salinity or do you want to say that the wind increased salinity and the rainfall decreased salinity?

**Comment by skdunnigan** [comment]
Wind, I guess. Good catch. Salinity increased with the winds and then decreased following the wind shifts and rainfall events. I'll clarify the statement.
