### ISSUE TITLE
PO4 at Pine Island

### ISSUE THREAD

**Issue by nikkidix** [GTMNERR/swmp-quarter-report#57]
I'm wondering about the high levels of PO4 at PI Jan - May. What were the dates of the dredging again? Could the PO4 be being released from sediments?

**Comment by skdunnigan** [comment]
I have a comment from 4/20/2023 where @katiepetrinec had asked us if we knew when it started. But we ended up having to reach out to Kaitlyn and I'm not sure if we got those dates anywhere. I'll see if it may be in the metadata.
