### ISSUE TITLE
Figure 4.3 comment

### ISSUE THREAD

**Issue by katiepetrinec** [GTMNERR/swmp-quarter-report#64]
Looking at the water temperature figures - I guess I hadn't really noticed this before, but I think that it is interesting to see how much cooler the daily range of water temperature is in the summer months at the inlet stations. San Sebastian, I get because it is so deep, but it is interesting to see that at FM too - cooler ocean water.

**Comment by skdunnigan** [comment]
Yea it is pretty neat to see that
