### ISSUE TITLE
5.1 Summary

### ISSUE THREAD

**Issue by katiepetrinec** [GTMNERR/swmp-quarter-report#65]
Paragraph 1, last sentence
Currently reads: Tables 5.1 and 5.2 show the hypoxia events and duration (more than 0.5 hrs) at Pine Island and Pellicer Creek for this year.

Suggested improvement: It would be helpful to include links to tables 5.1 and 5.2, if possible.

**Comment by mmhowkins** [comment]
Potentially fixing this issue in the paragraph adjusted the captions for tables 5.1 and 5.2. They now do not have captions and say 
"?(caption)"
