### ISSUE TITLE
Paragraph Included Links 

### ISSUE THREAD

**Issue by mmhowkins** [GTMNERR/swmp-quarter-report#85]
This is a weird, slightly nit-picky comment. 
In the Background section of the report, all of the links to websites within the paragraphs open a new tab in the browser for the user when clicked. However, in the Results section, all of the links to websites within the paragraphs open the link within the same tab in the browser.
I know that is a weird thing to comment on, but I noticed it while clicking all the links and was not sure if it was done on purpose or not!

**Comment by skdunnigan** [comment]
This issue is associated with #69 . I left it open since I wasn't sure whether to make some pages have these feature or to make a blanket yes or no for the entire report....still up for discussion. thoughts? @mmhowkins @katiepetrinec

**Comment by mmhowkins** [comment]
I am always a person who prefers for all links to automatically open a new page, however I do know there are people who do not like to have multiple webpages opening. 
I would prefer all to open separately, but a good compromise could be to have website links open a new page and figure links to stay in the same document for easy scrolling between parts of the report. 
Open to suggestions on that idea though!

**Comment by skdunnigan** [comment]
Unfortunately, the external links option applies to *all links* in a page (figures and weblinks). It would be nice to do what you suggested, @mmhowkins, but I don't know if this current setup would allow for that. So, the question would be...do we keep links opening to a new webpage across the whole report or do we allow for external links on the "background" style pages that don't have any data-related objects in them (like "Sites", "Background", and "QAQC")?
